/* SPDX-License-Identifier: MIT */
/** @file floquet_code.h
 *  @brief Floquet codes: a measurement schedule that periodically returns
 *         to a stabilizer code, with logical information encoded in the
 *         dynamics rather than a fixed code.
 *
 *  ## What is a Floquet code?
 *
 *  Unlike a static stabilizer code (a single fixed group of commuting
 *  Paulis), a **Floquet code** is defined by a time-periodic sequence
 *  of *measurements*. At each round `t ∈ {0, 1, ..., T-1}`, a list of
 *  Pauli operators is measured. The instantaneous stabilizer group
 *  (ISG) at the end of round `t` is generated by:
 *
 *    - The Paulis just measured in round `t` (and their products); and
 *    - All operators inherited from previous rounds that commute with
 *      every measurement performed since they were last in the ISG.
 *
 *  Crucially, the Paulis measured in different rounds need *not*
 *  commute pairwise across rounds — the ISG evolves from one round to
 *  the next, with each round's measurements potentially anti-commuting
 *  with some leftover ISG generators (which are then removed and
 *  replaced).
 *
 *  After `T` rounds, the ISG returns to its original form (up to a
 *  Pauli frame change), making the code "Floquet-periodic".
 *
 *  ## Why this matters
 *
 *  - **Honeycomb Floquet code** [Hastings-Haah 2021] — the breakthrough
 *    instance: a 3-color edge schedule on the hexagonal lattice with
 *    `T = 3` rounds, achieving threshold ~0.2-0.3% under measurement
 *    noise.
 *  - **CSS Floquet codes** [Davydova-Tantivasadakarn-Balasubramanian
 *    2023] — a generalisation with explicit logical operators and CSS
 *    structure within each round.
 *  - **Boundary Floquet codes** [Aasen et al. 2023] — Floquet codes on
 *    finite patches with rough/smooth boundaries.
 *
 *  Floquet codes are *fundamentally* more general than CSS codes. They
 *  cannot be reduced to a single H_X / H_Z pair; instead, each round
 *  has its own measurement support.
 *
 *  ## Storage
 *
 *  A Floquet code is a list of "rounds", where each round is a list of
 *  measurement operators (Paulis represented as `irrep_pauli_t`). The
 *  schedule is interpreted cyclically modulo `T = n_rounds`.
 *
 *  ## Primary references
 *
 *  - Hastings-Haah, *Dynamically generated logical qubits*, PRX Quantum
 *    2 (2021) 030328 [arXiv:2107.02194].
 *  - Haah-Hastings, *Boundaries for the honeycomb code*, Quantum 6
 *    (2022) 693.
 *  - Davydova-Tantivasadakarn-Balasubramanian, *Floquet codes without
 *    parent subsystem codes*, PRX Quantum 4 (2023) 020341.
 *  - Aasen-Bonderson-Knapp, *Adiabatic paths of Hamiltonians, symmetries
 *    of topological order, and automorphism codes*, Phys. Rev. B 106
 *    (2022) 085122 — automorphism-code framework.
 */
#ifndef IRREP_FLOQUET_CODE_H
#define IRREP_FLOQUET_CODE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <irrep/export.h>
#include <irrep/stabilizer_group.h>
#include <irrep/types.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @brief One round of measurements in a Floquet schedule.
 *
 *  Owns a heap-allocated array of `n_meas` Pauli operators (each on
 *  `n_qubits` qubits). The Paulis within a single round must
 *  pairwise commute — this is a *measurement* round, not just a list
 *  of arbitrary operators. */
typedef struct {
    int n_qubits;        /**< Number of physical qubits in the schedule. */
    int n_meas;          /**< Number of Pauli measurements this round. */
    irrep_pauli_t *meas; /**< Array of length `n_meas`. */
} irrep_floquet_round_t;

/** @brief A Floquet code: a periodic schedule of measurement rounds. */
typedef struct {
    int n_qubits;                /**< Number of physical qubits. */
    int n_rounds;                /**< Number of rounds in one period. */
    irrep_floquet_round_t *rounds; /**< Array of length `n_rounds`. */
} irrep_floquet_code_t;

/** @brief Allocate a Floquet code with the given number of qubits and
 *  rounds. Each round starts empty (n_meas = 0). */
IRREP_API irrep_status_t
irrep_floquet_code_new(irrep_floquet_code_t *out,
                       int n_qubits, int n_rounds);

/** @brief Free internal storage. */
IRREP_API void
irrep_floquet_code_free(irrep_floquet_code_t *f);

/** @brief Allocate the measurements for a specific round. */
IRREP_API irrep_status_t
irrep_floquet_round_alloc(irrep_floquet_code_t *f,
                          int round_index, int n_meas);

/** @brief Verify that the measurements within a single round pairwise
 *  commute (a precondition for being a valid measurement round). */
IRREP_API irrep_status_t
irrep_floquet_round_check_commutativity(const irrep_floquet_code_t *f,
                                        int round_index);

/** @brief Verify that **every** round in the schedule satisfies
 *  intra-round commutativity. */
IRREP_API irrep_status_t
irrep_floquet_code_check(const irrep_floquet_code_t *f);

/** @brief Materialise a single round as an `irrep_stabilizer_group_t`,
 *  ignoring inter-round inheritance. Useful for inspecting the
 *  "instantaneous code at round t". Caller must
 *  `irrep_stabilizer_group_free` when done. */
IRREP_API irrep_status_t
irrep_floquet_round_to_stabilizer_group(const irrep_floquet_code_t *f,
                                        int round_index,
                                        irrep_stabilizer_group_t *out);

#ifdef __cplusplus
}
#endif

#endif /* IRREP_FLOQUET_CODE_H */
