/* SPDX-License-Identifier: MIT */
/** @file qec_distance.h
 *  @brief Pauli multiplication, stabilizer-group membership, and
 *         brute-force code-distance computation.
 *
 *  ## Pauli multiplication
 *
 *  Given two Pauli operators in the symplectic representation `(x, z)`
 *  with signs in `{+1, +i, -1, -i}`, their product is:
 *
 *      P · Q = sign_P · sign_Q · (-1)^{Σᵢ z_P[i] · x_Q[i]}
 *               · ∏ X^{x_P[i]+x_Q[i] mod 2} Z^{z_P[i]+z_Q[i] mod 2}
 *
 *  The sign carry comes from commuting all `Z`s past all `X`s when
 *  combining `X^{x_P} Z^{z_P} · X^{x_Q} Z^{z_Q}`: each anti-commutation
 *  event flips the sign.
 *
 *  ## Stabilizer-group membership
 *
 *  A Pauli `p` is in the stabilizer group iff its symplectic vector
 *  `(x_p, z_p) ∈ F₂^{2n}` lies in the F₂-span of the generators'
 *  symplectic vectors. We test this by Gaussian elimination on the
 *  augmented matrix.
 *
 *  ## Brute-force distance
 *
 *  For a stabilizer code, the distance `d` is the minimum weight of a
 *  *non-trivial logical operator* — a Pauli that commutes with every
 *  stabilizer but is NOT in the stabilizer group. We enumerate all
 *  weight-`w` Paulis for `w = 1, 2, ...` until one is found, returning
 *  the first such `w`.
 *
 *  Complexity: `C(n, w) · 3^w` per weight class. Practical for `n ≤ 20`
 *  and weight up to ~6. For larger codes, use logical-operator-based
 *  upper bounds (e.g., known string operators in toric codes).
 */
#ifndef IRREP_QEC_DISTANCE_H
#define IRREP_QEC_DISTANCE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <irrep/export.h>
#include <irrep/stabilizer_group.h>
#include <irrep/types.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @brief Multiply two Pauli operators: out = p · q (in operator order).
 *
 *  The sign of `out` reflects the F₂ carry: each anti-commutation event
 *  between `Z_P` and `X_Q` contributes a factor of `-1`.
 *
 *  `out` must be allocated with the same `n` as `p` and `q`. */
IRREP_API irrep_status_t
irrep_pauli_multiply(irrep_pauli_t *out,
                     const irrep_pauli_t *p,
                     const irrep_pauli_t *q);

/** @brief Test whether the (signed-ignored) support of Pauli `p` lies in
 *  the F₂-span of the generators of stabilizer group `g`.
 *
 *  Returns 1 if `p`'s support is generated by `g`, 0 otherwise.
 *  Returns -1 on error. */
IRREP_API int
irrep_stabilizer_group_contains(const irrep_stabilizer_group_t *g,
                                const irrep_pauli_t *p);

/** @brief Compute the code distance by brute-force enumeration up to
 *  `max_weight`.
 *
 *  Iterates over all weight-`w` Paulis (for `w = 1, 2, ..., max_weight`)
 *  and returns the smallest `w` for which there exists a Pauli that
 *  commutes with all generators but is not in the group. If no such
 *  Pauli is found within `max_weight`, returns `max_weight + 1` to
 *  indicate the distance lower bound.
 *
 *  Complexity: O(C(n, w) · 3^w · m · n) per weight class (where m is the
 *  number of generators). Use for small codes only. */
IRREP_API int
irrep_qec_distance_brute(const irrep_stabilizer_group_t *g,
                         int max_weight);

#ifdef __cplusplus
}
#endif

#endif /* IRREP_QEC_DISTANCE_H */
