/* SPDX-License-Identifier: MIT */
/** @file subsystem_code.h
 *  @brief Subsystem (gauge) codes: stabilizer group + gauge group split.
 *
 *  ## What is a subsystem code?
 *
 *  A subsystem code (Poulin 2005, Bacon 2006) splits the Hilbert space
 *  into three tensor factors:
 *
 *      H_phys  =  C  ⊗  G  ⊗  R
 *
 *  where:
 *    - **C** carries the encoded *logical* qubits.
 *    - **G** carries the *gauge* qubits — auxiliary degrees of freedom
 *      that absorb the syndromes of the gauge generators.
 *    - **R** is the rest (kernel of the stabilizer group, fixed to a
 *      simultaneous +1 eigenstate).
 *
 *  Concretely, a subsystem code is specified by:
 *    - The **gauge group** `G` ⊆ Pauli group, possibly non-abelian.
 *      Generators: `irrep_pauli_t` list. Need NOT pairwise commute.
 *    - The **stabilizer group** `S = Z(G) ∩ G` (centre of `G`
 *      intersected with `G`). Always abelian. This is what one
 *      *measures* to detect errors.
 *    - The **bare logical operators** `L̄ ⊆ Z(G) \ S`: elements that
 *      commute with all gauge generators but are not in `S`.
 *    - The **dressed logical operators** `L = L̄ · G`: equivalence
 *      classes of bare logicals modulo gauge generators (since gauge
 *      generators are NOT measured, they can be applied for free).
 *
 *  ## Why subsystem codes matter
 *
 *  - **Bacon-Shor [[9, 1, 3]]** [Bacon 2006]: fault-tolerant on
 *    superconducting hardware with two-qubit gauge measurements only.
 *  - **Gauge color code** [Bombin 2010]: 3D color code with
 *    transversal universal gates — single-shot fault-tolerance.
 *  - **Subsystem surface code** [Bombin 2010]: the surface code with
 *    extra gauge generators that commute weakly within rounds.
 *  - **Bravyi-Kitaev subsystem codes**: building blocks for
 *    fault-tolerant Clifford operations.
 *
 *  ## Storage
 *
 *  We store the gauge group as a list of `irrep_pauli_t`s (the gauge
 *  generators), not requiring them to commute. Computing the stabilizer
 *  subgroup `S` requires finding the centre — for a list of `m_g`
 *  gauge generators, the stabilizer is generated by the elements that
 *  commute with every generator. We expose a primitive that returns
 *  one such element (or finds the full stabilizer subgroup).
 *
 *  ## Primary references
 *
 *  - Poulin, *Stabilizer formalism for operator quantum error correction*,
 *    Phys. Rev. Lett. 95 (2005) 230504.
 *  - Bacon, *Operator quantum error-correcting subsystems for
 *    self-correcting quantum memories*, Phys. Rev. A 73 (2006) 012340 —
 *    Bacon-Shor [[9,1,3]].
 *  - Bombín, *Topological subsystem codes*, Phys. Rev. A 81 (2010)
 *    032301 — gauge color codes.
 *  - Kribs-Laflamme-Poulin, *Operator quantum error correction*,
 *    Quantum Inf. Comput. 6 (2006) 382.
 */
#ifndef IRREP_SUBSYSTEM_CODE_H
#define IRREP_SUBSYSTEM_CODE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <irrep/export.h>
#include <irrep/stabilizer_group.h>
#include <irrep/types.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @brief A subsystem code: a list of gauge generators on `n` qubits.
 *
 *  Gauge generators are Pauli operators that need not pairwise commute.
 *  The stabilizer subgroup is the centre of the gauge group; the bare
 *  logical operators are elements of the centraliser `C(G) = Z(G^*)
 *  ∩ Pauli` modulo the stabilizer. */
typedef struct {
    int n;                       /**< Number of physical qubits. */
    int n_gauge;                 /**< Number of gauge generators. */
    irrep_pauli_t *gauge;        /**< Array of length `n_gauge`. */
} irrep_subsystem_code_t;

/** @brief Allocate a subsystem code with `n_gauge` un-initialised gauge
 *  generators. */
IRREP_API irrep_status_t
irrep_subsystem_code_new(irrep_subsystem_code_t *out,
                         int n_qubits, int n_gauge);

/** @brief Free internal storage. */
IRREP_API void
irrep_subsystem_code_free(irrep_subsystem_code_t *c);

/** @brief Check whether a Pauli operator is in the centraliser of the
 *  gauge group, i.e. commutes with every gauge generator.
 *
 *  Returns 1 if `p` commutes with all gauge generators, 0 otherwise.
 *  Centraliser elements are the bare-logical candidates; subset of them
 *  also commute with each other and form the stabilizer subgroup. */
IRREP_API int
irrep_subsystem_in_centraliser(const irrep_subsystem_code_t *c,
                               const irrep_pauli_t *p);

/** @brief Build the [[9, 1, 3]] Bacon-Shor subsystem code.
 *
 *  Layout: 9 qubits arranged in a 3×3 grid. Gauge generators are the
 *  six 2-body XX operators on horizontal pairs and the six 2-body ZZ
 *  operators on vertical pairs (12 gauge generators total, of weight 2).
 *  The stabilizer subgroup is generated by 6 weight-6 elements (rows of
 *  XX-products and columns of ZZ-products), giving k = n - 6 - dim(gauge
 *  generators that are *not* in the stabilizer) = 1. */
IRREP_API irrep_status_t
irrep_subsystem_bacon_shor_9_1_3(irrep_subsystem_code_t *out);

#ifdef __cplusplus
}
#endif

#endif /* IRREP_SUBSYSTEM_CODE_H */
