/* SPDX-License-Identifier: MIT */
/* 2D wallpaper / space-group tables over periodic lattices.
 *
 * Implementation strategy:
 *
 *   1. Look up the wallpaper-group origin O for the (lattice, wallpaper)
 *      pair. For square and triangular, O = (0, 0) (a lattice site). For
 *      honeycomb and kagome, O = hexagon centre.
 *
 *   2. Generate all point-group elements as 2×2 real matrices M_p. The full
 *      action is  r → M_p (r − O) + O  (translation-free, fixed origin).
 *
 *   3. For each point element p and each lattice site s, compute the image
 *      cartesian position and look up the site index. Build a hash from
 *      quantised positions to site indices so the lookup is O(1).
 *
 *   4. For each full group element g = t · P + p (t = cell translation,
 *      p = point-element index), precompose the point permutation with a
 *      translation permutation so
 *        π_g(s) = T_t(π_p(s))
 *      where T_t shifts cells by (dx_t, dy_t).
 *
 *   5. Validate every permutation is a bijection; if not (PBC breaks the
 *      symmetry), the builder reports failure.
 *
 * Memory cost for the 6×6 kagome cluster:
 *   order = 12 · 36 = 432, sites = 108  →  432 · 108 · 4 B ≈ 186 KB.
 * Double that for the cached inverse permutations: ≈ 373 KB. Still tiny.
 */

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <irrep/space_group.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

extern void irrep_set_error_(const char *fmt, ...);

/* -------------------------------------------------------------------------- *
 * Internal representation                                                    *
 * -------------------------------------------------------------------------- */

struct irrep_space_group {
    const irrep_lattice_t *lattice; /* borrowed reference */
    irrep_wallpaper_t      kind;
    int                    point_order;
    int                    num_sites;
    int                    order;

    int                   *perm;     /* order * num_sites */
    int                   *perm_inv; /* order * num_sites */
};

/* -------------------------------------------------------------------------- *
 * Wallpaper origin for each (lattice, wallpaper) pair                        *
 * -------------------------------------------------------------------------- */

static void origin_for_(const irrep_lattice_t *L, irrep_wallpaper_t kind, double O[2]) {
    (void)kind; /* currently origin depends only on lattice */
    switch (irrep_lattice_kind(L)) {
    case IRREP_LATTICE_SQUARE:
    case IRREP_LATTICE_TRIANGULAR:
        O[0] = 0.0;
        O[1] = 0.0;
        return;
    case IRREP_LATTICE_HONEYCOMB:
        /* Hexagon centre, equidistant (1) from the 6 honeycomb sites. */
        O[0] = 0.5;
        O[1] = 0.5 * sqrt(3.0);
        return;
    case IRREP_LATTICE_KAGOME:
        /* Hexagon centre, equidistant (1) from the 6 kagome sites
         * {B(0,0), A(1,0), C(1,0), B(0,1), A(0,1), C(0,0)}. */
        O[0] = 1.5;
        O[1] = 0.5 * sqrt(3.0);
        return;
    }
    O[0] = 0.0;
    O[1] = 0.0;
}

/* -------------------------------------------------------------------------- *
 * Point-group matrix generation                                              *
 *                                                                            *
 * We store each point-group element as a row-major 2×2 double matrix. The   *
 * point groups are symmorphic; they are generated by a rotation and a       *
 * reflection, and all elements are listed with E first.                     *
 * -------------------------------------------------------------------------- */

static void rot_mat_(double theta, double M[4]) {
    double c = cos(theta), s = sin(theta);
    M[0] = c;
    M[1] = -s;
    M[2] = s;
    M[3] = c;
}

static void mat_mul_(const double A[4], const double B[4], double out[4]) {
    double r[4];
    r[0] = A[0] * B[0] + A[1] * B[2];
    r[1] = A[0] * B[1] + A[1] * B[3];
    r[2] = A[2] * B[0] + A[3] * B[2];
    r[3] = A[2] * B[1] + A[3] * B[3];
    memcpy(out, r, sizeof r);
}

/* Fill p4mm (order 8): E, C4, C2, C4^3, σ_x, σ_y, σ_d, σ_ad. */
static int fill_p4mm_(double mats[][4]) {
    /* rotations */
    rot_mat_(0.0, mats[0]);
    rot_mat_(0.5 * M_PI, mats[1]);
    rot_mat_(1.0 * M_PI, mats[2]);
    rot_mat_(1.5 * M_PI, mats[3]);
    /* σ_x: y → -y */
    mats[4][0] = 1.0;
    mats[4][1] = 0.0;
    mats[4][2] = 0.0;
    mats[4][3] = -1.0;
    /* σ_y: x → -x */
    mats[5][0] = -1.0;
    mats[5][1] = 0.0;
    mats[5][2] = 0.0;
    mats[5][3] = 1.0;
    /* σ_d: x ↔ y */
    mats[6][0] = 0.0;
    mats[6][1] = 1.0;
    mats[6][2] = 1.0;
    mats[6][3] = 0.0;
    /* σ_ad: x → -y, y → -x */
    mats[7][0] = 0.0;
    mats[7][1] = -1.0;
    mats[7][2] = -1.0;
    mats[7][3] = 0.0;
    return 8;
}

/* Fill p6mm (order 12): 6 rotations (E, C6, C3, C2, C3^2, C6^5), then 6 mirrors
 * generated as σ_v · rotation, where σ_v: y → -y. */
static int fill_p6mm_(double mats[][4]) {
    double sigma_v[4] = {1.0, 0.0, 0.0, -1.0};
    for (int k = 0; k < 6; ++k) {
        rot_mat_((double)k * M_PI / 3.0, mats[k]);
    }
    for (int k = 0; k < 6; ++k) {
        mat_mul_(sigma_v, mats[k], mats[6 + k]);
    }
    return 12;
}

/* Fill p2 (order 2): identity + 180° rotation. Works on every lattice;
 * a 180°-rotation (which is −I in 2D) is always a symmetry of any
 * Bravais lattice around any lattice site. No `Lx = Ly` constraint. */
static int fill_p2_(double mats[][4]) {
    rot_mat_(0.0, mats[0]);
    rot_mat_(M_PI, mats[1]);
    return 2;
}

/* Fill p6 (order 6): six proper rotations on a hexagonal lattice. Chiral —
 * no reflections. Subgroup of p6mm. */
static int fill_p6_(double mats[][4]) {
    for (int k = 0; k < 6; ++k)
        rot_mat_((double)k * M_PI / 3.0, mats[k]);
    return 6;
}

/* Fill p3m1 (order 6): three C_3 rotations + three σ_v mirrors through
 * the rotation centre. Convention: σ_v mirrors the y-axis (maps y → −y)
 * and its C_3-conjugates. The mirror axes pass through the vertices of
 * the hexagonal Wigner-Seitz cell. */
static int fill_p3m1_(double mats[][4]) {
    /* Rotations E, C_3, C_3² at slots 0, 1, 2. */
    for (int k = 0; k < 3; ++k)
        rot_mat_(2.0 * (double)k * M_PI / 3.0, mats[k]);
    /* Mirrors σ_v · rotation at slots 3, 4, 5. */
    double sigma_v[4] = {1.0, 0.0, 0.0, -1.0};
    for (int k = 0; k < 3; ++k)
        mat_mul_(sigma_v, mats[k], mats[3 + k]);
    return 6;
}

/* Fill p31m (order 6): three C_3 rotations + three mirrors whose axes
 * bisect the vertex pairs of the hexagonal cell — 30° rotated relative
 * to p3m1's mirror placement. Built by conjugating the p3m1 mirror
 * generator by R(30°): σ_d = R(30°) · σ_v · R(−30°). */
static int fill_p31m_(double mats[][4]) {
    /* Rotations E, C_3, C_3² at slots 0, 1, 2. */
    for (int k = 0; k < 3; ++k)
        rot_mat_(2.0 * (double)k * M_PI / 3.0, mats[k]);
    /* σ_d = R(π/6) · σ_v · R(−π/6). */
    double sigma_v[4]  = {1.0, 0.0, 0.0, -1.0};
    double R30[4], Rm30[4], tmp[4], sigma_d[4];
    rot_mat_(+M_PI / 6.0, R30);
    rot_mat_(-M_PI / 6.0, Rm30);
    mat_mul_(sigma_v, Rm30, tmp);
    mat_mul_(R30, tmp, sigma_d);
    /* Mirrors σ_d · rotation at slots 3, 4, 5. */
    for (int k = 0; k < 3; ++k)
        mat_mul_(sigma_d, mats[k], mats[3 + k]);
    return 6;
}

/* Fill p4 (order 4): chiral square — E, C_4, C_2, C_4³. Subgroup of
 * p4mm with the mirrors stripped. */
static int fill_p4_(double mats[][4]) {
    for (int k = 0; k < 4; ++k)
        rot_mat_((double)k * M_PI / 2.0, mats[k]);
    return 4;
}

/* Fill p4gm (order 8): the non-symmorphic square group. Rotation block is
 * identical to p4mm's {E, C_4, C_2, C_4³}; the four mirrors each carry a
 * glide translation of ½(a_1 + a_2) (lattice basis) applied AFTER the
 * reflection. p4gm is distinct from p4mm precisely because the mirror
 * element's fixed-point set sits on glide-lines rather than through the
 * lattice origin, so the permutations differ on any cluster that can
 * distinguish a glide from an origin-fixing reflection.
 *
 * Fills both the 2×2 rotation matrix and the lattice-basis fractional
 * translation (output parameter `t_frac`, same length as `mats`). The caller
 * converts `t_frac` to cartesian by multiplying against the lattice's
 * primitive vectors: `t_cart = t_frac[0] · a_1 + t_frac[1] · a_2`. */
static int fill_p4gm_(double mats[][4], double t_frac[][2]) {
    /* Rotations at slots 0..3: zero glide. */
    for (int k = 0; k < 4; ++k) {
        rot_mat_((double)k * M_PI / 2.0, mats[k]);
        t_frac[k][0] = 0.0;
        t_frac[k][1] = 0.0;
    }
    /* Mirrors at slots 4..7 — same axes as p4mm (σ_x, σ_y, σ_d, σ_ad) but
     * with a ½·(a_1 + a_2) glide translation applied after the reflection. */
    /* σ_x: y → −y */
    mats[4][0] = 1.0;  mats[4][1] = 0.0;  mats[4][2] = 0.0;  mats[4][3] = -1.0;
    /* σ_y: x → −x */
    mats[5][0] = -1.0; mats[5][1] = 0.0;  mats[5][2] = 0.0;  mats[5][3] = 1.0;
    /* σ_d: x ↔ y */
    mats[6][0] = 0.0;  mats[6][1] = 1.0;  mats[6][2] = 1.0;  mats[6][3] = 0.0;
    /* σ_ad: (x, y) → (−y, −x) */
    mats[7][0] = 0.0;  mats[7][1] = -1.0; mats[7][2] = -1.0; mats[7][3] = 0.0;
    for (int k = 4; k < 8; ++k) {
        t_frac[k][0] = 0.5;
        t_frac[k][1] = 0.5;
    }
    return 8;
}

/* -------------------------------------------------------------------------- *
 * Site-finding by exact lattice-coordinate inversion.                        *
 *                                                                            *
 * Given a cartesian image r_img and the primitive basis (a1, a2), for each   *
 * sublattice s we solve (ax, ay) from                                        *
 *     r_img − δ_s = ax · a1 + ay · a2                                        *
 * If (ax, ay) rounds to integers within tolerance, the image is a lattice    *
 * site on sublattice s at cell (ax mod Lx, ay mod Ly). This is robust to     *
 * trig-introduced floating-point noise from the point-group matrix, unlike   *
 * a quantised-position hash where ULP-level differences can flip the hit.    *
 * -------------------------------------------------------------------------- */

typedef struct {
    double a1[2], a2[2];
    double inv[4]; /* row-major inverse of [[a1x a2x][a1y a2y]] */
    int    sites_per_cell;
    int    Lx, Ly;
    double sublattice_xy[6]; /* up to 3 sublattices × 2 components */
} invbasis_t;

static void invbasis_init_(invbasis_t *B, const irrep_lattice_t *L) {
    irrep_lattice_primitive_vectors(L, B->a1, B->a2);
    /* Row-major M = [[a1x, a2x], [a1y, a2y]]; inv = (1/det) · [[a2y, -a2x], [-a1y, a1x]] */
    double det = B->a1[0] * B->a2[1] - B->a2[0] * B->a1[1];
    double s = 1.0 / det;
    B->inv[0] = s * B->a2[1];
    B->inv[1] = -s * B->a2[0];
    B->inv[2] = -s * B->a1[1];
    B->inv[3] = s * B->a1[0];
    B->sites_per_cell = irrep_lattice_sites_per_cell(L);
    B->Lx = irrep_lattice_Lx(L);
    B->Ly = irrep_lattice_Ly(L);
    for (int sub = 0; sub < B->sites_per_cell; ++sub) {
        /* Each sublattice's δ_s relative to cell origin (ix=iy=0, sub=0). */
        double xy[2];
        int    s0 = irrep_lattice_site_index(L, 0, 0, sub);
        irrep_lattice_site_position(L, s0, xy);
        B->sublattice_xy[2 * sub + 0] = xy[0];
        B->sublattice_xy[2 * sub + 1] = xy[1];
    }
}

static int nonneg_mod_(int x, int m) {
    int r = x % m;
    return r < 0 ? r + m : r;
}

/* Locate the lattice-site index whose cartesian position matches r_img
 * (modulo PBC), or -1 if the image is not on the lattice. Tolerance is
 * 1e-8 in lattice-coordinate units, plenty of headroom for the cos/sin
 * noise introduced by the rotation matrix. */
static int find_site_by_inv_(const invbasis_t *B, const irrep_lattice_t *L, const double r_img[2]) {
    for (int sub = 0; sub < B->sites_per_cell; ++sub) {
        double dx = r_img[0] - B->sublattice_xy[2 * sub + 0];
        double dy = r_img[1] - B->sublattice_xy[2 * sub + 1];
        double ax = B->inv[0] * dx + B->inv[1] * dy;
        double ay = B->inv[2] * dx + B->inv[3] * dy;
        long   ix = (long)lround(ax);
        long   iy = (long)lround(ay);
        if (fabs(ax - (double)ix) < 1e-8 && fabs(ay - (double)iy) < 1e-8) {
            return irrep_lattice_site_index(L, nonneg_mod_((int)ix, B->Lx),
                                            nonneg_mod_((int)iy, B->Ly), sub);
        }
    }
    return -1;
}

/* -------------------------------------------------------------------------- *
 * Permutation construction                                                   *
 * -------------------------------------------------------------------------- */

/* Apply a space-group operation r → M · (r − O) + O + t_cartesian to one
 * cartesian point. `t_cart` is the fractional glide translation expressed in
 * cartesian coordinates (zero for every symmorphic group operation). */
static int apply_point_(const double M[4], const double O[2], const double t_cart[2],
                        const double r[2], double out[2]) {
    double d[2] = {r[0] - O[0], r[1] - O[1]};
    out[0] = M[0] * d[0] + M[1] * d[1] + O[0] + t_cart[0];
    out[1] = M[2] * d[0] + M[3] * d[1] + O[1] + t_cart[1];
    return 0;
}

static int build_point_perm_(const irrep_lattice_t *L, const double M[4], const double O[2],
                             const double t_cart[2], const invbasis_t *B, int *perm_out) {
    int n = irrep_lattice_num_sites(L);
    for (int s = 0; s < n; ++s) {
        double r[2];
        irrep_lattice_site_position(L, s, r);
        double r_img[2];
        apply_point_(M, O, t_cart, r, r_img);
        int image = find_site_by_inv_(B, L, r_img);
        if (image < 0)
            return -1;
        perm_out[s] = image;
    }
    return 0;
}

static int is_valid_perm_(const int *perm, int n, unsigned char *scratch) {
    memset(scratch, 0, (size_t)n);
    for (int s = 0; s < n; ++s) {
        int image = perm[s];
        if (image < 0 || image >= n || scratch[image])
            return 0;
        scratch[image] = 1;
    }
    return 1;
}

/* -------------------------------------------------------------------------- *
 * Public API                                                                 *
 * -------------------------------------------------------------------------- */

irrep_space_group_t *irrep_space_group_build(const irrep_lattice_t *L, irrep_wallpaper_t kind) {
    if (!L) {
        irrep_set_error_("irrep_space_group_build: NULL lattice");
        return NULL;
    }

    /* Validate (lattice, wallpaper) compatibility and fill point matrices. */
    double mats[12][4];
    /* Per-element fractional (lattice-basis) translation. Zero for symmorphic
     * groups; non-zero on non-symmorphic groups like p4gm (glide mirrors). */
    double t_frac[12][2] = {{0}};
    int    point_order = 0;
    /* Whether this wallpaper group requires Lx == Ly (for C_4 / C_3 / C_6
     * lattice symmetry preservation on the torus). p1 and p2 (trivial or
     * 180° rotation) work on every cluster. */
    int    needs_square_cluster = 1;
    switch (kind) {
    case IRREP_WALLPAPER_P1:
        point_order = 1;
        mats[0][0] = 1;
        mats[0][1] = 0;
        mats[0][2] = 0;
        mats[0][3] = 1;
        needs_square_cluster = 0;
        break;
    case IRREP_WALLPAPER_P2:
        point_order = fill_p2_(mats);
        /* 180° rotation is a symmetry of any Bravais lattice torus;
         * Lx and Ly are free. */
        needs_square_cluster = 0;
        break;
    case IRREP_WALLPAPER_P4MM:
        if (irrep_lattice_kind(L) != IRREP_LATTICE_SQUARE) {
            irrep_set_error_("irrep_space_group_build: p4mm requires the square lattice");
            return NULL;
        }
        point_order = fill_p4mm_(mats);
        break;
    case IRREP_WALLPAPER_P6MM:
        if (irrep_lattice_kind(L) == IRREP_LATTICE_SQUARE) {
            irrep_set_error_("irrep_space_group_build: p6mm not compatible with square lattice");
            return NULL;
        }
        point_order = fill_p6mm_(mats);
        break;
    case IRREP_WALLPAPER_P6:
        if (irrep_lattice_kind(L) == IRREP_LATTICE_SQUARE) {
            irrep_set_error_("irrep_space_group_build: p6 not compatible with square lattice");
            return NULL;
        }
        point_order = fill_p6_(mats);
        break;
    case IRREP_WALLPAPER_P3M1:
        if (irrep_lattice_kind(L) == IRREP_LATTICE_SQUARE) {
            irrep_set_error_("irrep_space_group_build: p3m1 not compatible with square lattice");
            return NULL;
        }
        point_order = fill_p3m1_(mats);
        break;
    case IRREP_WALLPAPER_P31M:
        if (irrep_lattice_kind(L) == IRREP_LATTICE_SQUARE) {
            irrep_set_error_("irrep_space_group_build: p31m not compatible with square lattice");
            return NULL;
        }
        point_order = fill_p31m_(mats);
        break;
    case IRREP_WALLPAPER_P4:
        if (irrep_lattice_kind(L) != IRREP_LATTICE_SQUARE) {
            irrep_set_error_("irrep_space_group_build: p4 requires the square lattice");
            return NULL;
        }
        point_order = fill_p4_(mats);
        break;
    case IRREP_WALLPAPER_P4GM:
        /* The non-symmorphic p4gm carries a ½·(a_1 + a_2) glide on each of
         * its four mirrors. On the single-sublattice square lattice the
         * glide maps site (i, j) → (i+½, −j+½), which is not a lattice
         * site — every glide-mirror permutation would attempt to
         * reference an off-lattice position. Until a two-basis square
         * lattice ships (e.g. `IRREP_LATTICE_SQUARE_2BASIS`) there is no
         * supported (lattice, p4gm) combination; reject at build time
         * with a clear diagnostic. The fractional-translation plumbing
         * below (`fill_p4gm_`, `t_frac` → `t_cart` in `build_point_perm_`)
         * is in place and would take effect on a compatible lattice. */
        irrep_set_error_("irrep_space_group_build: p4gm is non-symmorphic and requires a "
                         "two-basis square lattice; no currently-shipped lattice kind "
                         "supports it (the single-sublattice square maps glide images "
                         "off the integer-site set).");
        return NULL;
    default:
        irrep_set_error_("irrep_space_group_build: unknown wallpaper kind %d", (int)kind);
        return NULL;
    }

    int Lx = irrep_lattice_Lx(L), Ly = irrep_lattice_Ly(L);
    if (needs_square_cluster && Lx != Ly) {
        irrep_set_error_("irrep_space_group_build: wallpaper kind %d requires Lx == Ly (got %d × %d)",
                         (int)kind, Lx, Ly);
        return NULL;
    }

    double O[2];
    origin_for_(L, kind, O);
    invbasis_t B;
    invbasis_init_(&B, L);

    int n = irrep_lattice_num_sites(L);
    int num_cells = irrep_lattice_num_cells(L);

    /* Point-permutations: point_order × n */
    int *pperm = malloc((size_t)point_order * (size_t)n * sizeof(int));
    if (!pperm) {
        irrep_set_error_("irrep_space_group_build: out of memory (point permutations)");
        return NULL;
    }
    unsigned char *validate = malloc((size_t)n);
    if (!validate) {
        free(pperm);
        irrep_set_error_("irrep_space_group_build: out of memory (validate)");
        return NULL;
    }
    for (int p = 0; p < point_order; ++p) {
        int *slot = pperm + (size_t)p * n;
        /* Convert the (possibly-nonzero) lattice-basis glide translation
         * to cartesian via the lattice primitives. Zero for symmorphic
         * groups — the existing code path is preserved bit-for-bit. */
        double t_cart[2] = {
            t_frac[p][0] * B.a1[0] + t_frac[p][1] * B.a2[0],
            t_frac[p][0] * B.a1[1] + t_frac[p][1] * B.a2[1],
        };
        if (build_point_perm_(L, mats[p], O, t_cart, &B, slot) != 0 ||
            !is_valid_perm_(slot, n, validate)) {
            free(validate);
            free(pperm);
            irrep_set_error_("irrep_space_group_build: cluster does not respect the wallpaper "
                             "group (element %d)",
                             p);
            return NULL;
        }
    }
    free(validate);

    /* Full table: order = num_cells × point_order. Enumeration convention:
     *   g = (ty · Lx + tx) · point_order + p
     * i.e. cell translations outermost, point-group elements innermost. */
    int  order = num_cells * point_order;
    int *perm = malloc((size_t)order * (size_t)n * sizeof(int));
    int *perm_inv = malloc((size_t)order * (size_t)n * sizeof(int));
    if (!perm || !perm_inv) {
        free(perm);
        free(perm_inv);
        free(pperm);
        irrep_set_error_("irrep_space_group_build: out of memory (full permutations)");
        return NULL;
    }

    /* Pre-compute per-site: (ix, iy, sub) for translation application. */
    int *site_ix = malloc((size_t)n * sizeof(int));
    int *site_iy = malloc((size_t)n * sizeof(int));
    int *site_sub = malloc((size_t)n * sizeof(int));
    if (!site_ix || !site_iy || !site_sub) {
        free(site_ix);
        free(site_iy);
        free(site_sub);
        free(perm);
        free(perm_inv);
        free(pperm);
        irrep_set_error_("irrep_space_group_build: out of memory (site cache)");
        return NULL;
    }
    for (int s = 0; s < n; ++s) {
        int ix, iy;
        irrep_lattice_cell_of(L, s, &ix, &iy);
        site_ix[s] = ix;
        site_iy[s] = iy;
        site_sub[s] = irrep_lattice_sublattice_of(L, s);
    }

    for (int tx = 0; tx < Lx; ++tx) {
        for (int ty = 0; ty < Ly; ++ty) {
            int tidx = ty * Lx + tx;
            for (int p = 0; p < point_order; ++p) {
                int        g = tidx * point_order + p;
                int       *out = perm + (size_t)g * n;
                int       *out_i = perm_inv + (size_t)g * n;
                const int *pslot = pperm + (size_t)p * n;
                for (int s = 0; s < n; ++s) {
                    int mid = pslot[s];
                    int nsite = irrep_lattice_site_index(L, site_ix[mid] + tx, site_iy[mid] + ty,
                                                         site_sub[mid]);
                    out[s] = nsite;
                }
                for (int s = 0; s < n; ++s)
                    out_i[out[s]] = s;
            }
        }
    }

    free(site_ix);
    free(site_iy);
    free(site_sub);
    free(pperm);

    irrep_space_group_t *G = calloc(1, sizeof(*G));
    if (!G) {
        free(perm);
        free(perm_inv);
        irrep_set_error_("irrep_space_group_build: out of memory (handle)");
        return NULL;
    }
    G->lattice = L;
    G->kind = kind;
    G->point_order = point_order;
    G->num_sites = n;
    G->order = order;
    G->perm = perm;
    G->perm_inv = perm_inv;
    return G;
}

void irrep_space_group_free(irrep_space_group_t *G) {
    if (!G)
        return;
    free(G->perm);
    free(G->perm_inv);
    free(G);
}

int irrep_space_group_order(const irrep_space_group_t *G) {
    return G ? G->order : 0;
}
int irrep_space_group_point_order(const irrep_space_group_t *G) {
    return G ? G->point_order : 0;
}
int irrep_space_group_num_sites(const irrep_space_group_t *G) {
    return G ? G->num_sites : 0;
}

irrep_wallpaper_t irrep_space_group_kind(const irrep_space_group_t *G) {
    return G ? G->kind : IRREP_WALLPAPER_P1;
}

const irrep_lattice_t *irrep_space_group_lattice(const irrep_space_group_t *G) {
    return G ? G->lattice : NULL;
}

int irrep_space_group_apply(const irrep_space_group_t *G, int g, int site) {
    if (!G)
        return -1;
    if (g < 0 || g >= G->order || site < 0 || site >= G->num_sites)
        return -1;
    return G->perm[(size_t)g * G->num_sites + site];
}

void irrep_space_group_permutation(const irrep_space_group_t *G, int g, int *perm) {
    if (!G || !perm || g < 0 || g >= G->order)
        return;
    memcpy(perm, G->perm + (size_t)g * G->num_sites, (size_t)G->num_sites * sizeof(int));
}

void irrep_space_group_permutation_inverse(const irrep_space_group_t *G, int g, int *perm) {
    if (!G || !perm || g < 0 || g >= G->order)
        return;
    memcpy(perm, G->perm_inv + (size_t)g * G->num_sites, (size_t)G->num_sites * sizeof(int));
}

void irrep_space_group_apply_config(const irrep_space_group_t *G, int g, const double *in,
                                    double *out) {
    if (!G || !in || !out)
        return;
    if (g < 0 || g >= G->order)
        return;
    const int *inv = G->perm_inv + (size_t)g * G->num_sites;
    for (int s = 0; s < G->num_sites; ++s)
        out[s] = in[inv[s]];
}

uint64_t irrep_space_group_apply_bits(const irrep_space_group_t *G, int g,
                                      uint64_t config_in) {
    if (!G || g < 0 || g >= G->order)
        return config_in;
    int N = G->num_sites;
    if (N > 64)
        return config_in;
    const int *perm = G->perm + (size_t)g * N;
    uint64_t   out  = 0;
    for (int i = 0; i < N; ++i) {
        if ((config_in >> i) & 1ULL)
            out |= (uint64_t)1 << perm[i];
    }
    return out;
}
